// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_level_80 = "CgkIueyZo70MEAIQDQ"; // <GPGSID>
        public const string achievement_level_90 = "CgkIueyZo70MEAIQDg"; // <GPGSID>
        public const string achievement_level_15 = "CgkIueyZo70MEAIQBQ"; // <GPGSID>
        public const string achievement_level_25 = "CgkIueyZo70MEAIQBw"; // <GPGSID>
        public const string achievement_level_5 = "CgkIueyZo70MEAIQAw"; // <GPGSID>
        public const string achievement_newbie = "CgkIueyZo70MEAIQAg"; // <GPGSID>
        public const string achievement_legendary = "CgkIueyZo70MEAIQDw"; // <GPGSID>
        public const string leaderboard_leaderboard = "CgkIueyZo70MEAIQAQ"; // <GPGSID>
        public const string achievement_level_40 = "CgkIueyZo70MEAIQCQ"; // <GPGSID>
        public const string achievement_master = "CgkIueyZo70MEAIQCA"; // <GPGSID>
        public const string achievement_level_60 = "CgkIueyZo70MEAIQCw"; // <GPGSID>
        public const string achievement_level_70 = "CgkIueyZo70MEAIQDA"; // <GPGSID>
        public const string achievement_level_10 = "CgkIueyZo70MEAIQBA"; // <GPGSID>
        public const string achievement_level_20 = "CgkIueyZo70MEAIQBg"; // <GPGSID>
        public const string achievement_grand_master = "CgkIueyZo70MEAIQCg"; // <GPGSID>

}

